version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          command: yarn && yarn dev:build
